version: "3.7" 
services:
  nginx:
    image: nginx:1.13
    volumes:
      - "./estudo:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - php

  # Application service layer
  php:
    build:
      context: ./php
    volumes:
      - "./estudo:/var/www/html"
    ports:
      - "9000:9000"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=estudoPZP

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estudoPZP
  
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links: 
          - db:db
      ports:
          - 8000:80
      environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root